### ISSUE TITLE
Proposal: Themes Support

### ISSUE THREAD

**Issue by antfu** [wenyan-lang/ide#2]
Themes could make the IDE more customizable for programmers' personal preferences, we could also include some popular themes like Monokai, Solarized Dark/Light, etc built-in for users to choose. (and also configurable for embedding)

I propose this format, it could be a simple js object or even store as JSON. 

```js
{
   background: "#fff",
   foreground: "#111",
   primary: "red",
   secondary: "rgba(23,14,45,0.4)",
   // ...
}
// If the provided fields are incomplete, they will fall back to the default values.
```

Furthermore, we could have some metadata as well

```js
{
  name: "Wenyan Dark",
  author: "Wenyan Team",
  isDark: true,
  theme: {
    background: "black",
    foreground: "#fff",
    primary: "red",
    secondary: "rgba(23,14,45,0.4)",
    // ...
  }
}
```

By this, we can also get rid of the "dark mode" hack since it also inverts the colors in the output canvas which may be kinda confusing for painting. 

When we grow a number of themes, we could also generate themes for CodeMirror and Prism.js that can be directly pulled from CDN in https://github.com/wenyan-lang/highlight

**Comment by LingDong-** [comment]
Sounds great 👍
